 #"Renamed Columns2" = Table.RenameColumns(#"Filtered Rows",{{"Release Date", "Release Date 0"}}),
    #"Added Custom11" = Table.AddColumn(#"Renamed Columns2", "Revenue Month 0", each [Revenue] * 12/78),
    #"Added Custom" = Table.AddColumn(#"Added Custom11", "Release Date + 1", each Date.AddMonths([Release Date 0], 1)),
    #"Added Custom12" = Table.AddColumn(#"Added Custom", "Revenue Month 1", each [Revenue] * 11/78),
    #"Added Custom1" = Table.AddColumn(#"Added Custom12", "Release Date + 2", each Date.AddMonths([Release Date 0], 2)),
    #"Added Custom13" = Table.AddColumn(#"Added Custom1", "Revenue Month 2", each [Revenue] * 10/78),
    #"Added Custom2" = Table.AddColumn(#"Added Custom13", "Release Date + 3", each Date.AddMonths([Release Date 0], 3)),
    #"Added Custom14" = Table.AddColumn(#"Added Custom2", "Revenue Month 3", each [Revenue] * 9/78),
    #"Added Custom3" = Table.AddColumn(#"Added Custom14", "Release Date + 4", each Date.AddMonths([Release Date 0], 4)),
    #"Added Custom15" = Table.AddColumn(#"Added Custom3", "Revenue Month 4", each [Revenue] * 8/78),    
    #"Added Custom4" = Table.AddColumn(#"Added Custom15", "Release Date + 5", each Date.AddMonths([Release Date 0], 5)),
    #"Added Custom16" = Table.AddColumn(#"Added Custom4", "Revenue Month 5", each [Revenue] * 7/78),    
    #"Added Custom5" = Table.AddColumn(#"Added Custom16", "Release Date + 6", each Date.AddMonths([Release Date 0], 6)),
    #"Added Custom17" = Table.AddColumn(#"Added Custom5", "Revenue Month 6", each [Revenue] * 6/78),    
    #"Added Custom6" = Table.AddColumn(#"Added Custom17", "Release Date + 7", each Date.AddMonths([Release Date 0], 7)),
    #"Added Custom18" = Table.AddColumn(#"Added Custom6", "Revenue Month 7", each [Revenue] * 5/78),    
    #"Added Custom7" = Table.AddColumn(#"Added Custom18", "Release Date + 8", each Date.AddMonths([Release Date 0], 8)),
    #"Added Custom19" = Table.AddColumn(#"Added Custom7", "Revenue Month 8", each [Revenue] * 4/78),    
    #"Added Custom8" = Table.AddColumn(#"Added Custom19", "Release Date + 9", each Date.AddMonths([Release Date 0], 9)),
    #"Added Custom20" = Table.AddColumn(#"Added Custom8", "Revenue Month 9", each [Revenue] * 3/78),    
    #"Added Custom9" = Table.AddColumn(#"Added Custom20", "Release Date + 10", each Date.AddMonths([Release Date 0], 10)),
    #"Added Custom21" = Table.AddColumn(#"Added Custom9", "Revenue Month 10", each [Revenue] * 2/78),    
    #"Added Custom10" = Table.AddColumn(#"Added Custom21", "Release Date + 11", each Date.AddMonths([Release Date 0], 11)),
    #"Added Custom22" = Table.AddColumn(#"Added Custom10", "Revenue Month 11", each [Revenue] * 1/78),
    #"Removed Columns4" = Table.RemoveColumns(#"Added Custom22",{"Revenue"}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns4", {"IMDB ID"}, "Attribute", "Value"),
    #"Added Custom23" = Table.AddColumn(#"Unpivoted Other Columns", "Date", each if Value.Is([Value], type date) = true then [Value] else null),
    #"Added Custom24" = Table.AddColumn(#"Added Custom23", "Revenue", each if [Date] = null then [Value] else null),
    #"Split Column by Position" = Table.SplitColumn(#"Added Custom24", "Attribute", Splitter.SplitTextByPositions({0, 2}, true), {"Attribute.1", "Attribute.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Position",{{"Attribute.1", type text}, {"Attribute.2", Int64.Type}}),
    #"Removed Columns5" = Table.RemoveColumns(#"Changed Type2",{"Attribute.1", "Value"}),
    #"Grouped Rows" = Table.Group(#"Removed Columns5", {"IMDB ID", "Attribute.2"}, {{"Date", each List.Max([Date]), type nullable date}, {"Revenue", each List.Sum([Revenue]), type nullable number}}),
    #"Removed Columns6" = Table.RemoveColumns(#"Grouped Rows",{"Attribute.2"})
in
    #"Removed Columns6"